import { UserData, ProjectData } from "../api";

export const USERS: UserData[] = [
  { "id": 0, "name": "James Smith" }, // 0
  { "id": 1, "name": "Maria Garcia" }, // 5
  { "id": 2, "name": "Robert Johnson" }, // 15
  { "id": 3, "name": "Jennifer Lee" }, // 4
  { "id": 4, "name": "Michael Graham" }, // 16
  { "id": 5, "name": "Linda Davis" }, // 14
  { "id": 6, "name": "William Jones" }, // 11
  { "id": 7, "name": "Emily Martinez" }, // 10
  { "id": 8, "name": "David Wilson" }, // 12
  { "id": 9, "name": "Jessica Taylor" } // 13
];

export const PROJECTS: ProjectData[] = [
  { "id": 0, "title": "Market Trend Analysis", "creatorId": 1 },
  { "id": 1, "title": "Consumer Behavior Study", "creatorId": 1 },
  { "id": 2, "title": "Sales Forecast Model", "creatorId": 1 },
  { "id": 3, "title": "Operational Efficiency Review", "creatorId": 1 },
  { "id": 4, "title": "Investment Portfolio Analysis", "creatorId": 5 },
  { "id": 5, "title": "Customer Segmentation Insight", "creatorId": 2 },
  { "id": 6, "title": "Risk Assessment Report", "creatorId": 2 },
  { "id": 7, "title": "Product Development Strategy", "creatorId": 2 },
  { "id": 8, "title": "Investment Portfolio Analysis", "creatorId": 2 },
  { "id": 9, "title": "Resource Allocation Plan", "creatorId": 2 },
  { "id": 10, "title": "Competitive Landscape Mapping", "creatorId": 3 },
  { "id": 11, "title": "User Engagement Metrics", "creatorId": 3 },
  { "id": 12, "title": "Healthcare Outcomes Research", "creatorId": 2 },
  { "id": 13, "title": "Market Trend Analysis", "creatorId": 4 },
  { "id": 14, "title": "Consumer Behavior Study", "creatorId": 4 },
  { "id": 15, "title": "Sales Forecast Model", "creatorId": 4 },
  { "id": 16, "title": "Operational Efficiency Review", "creatorId": 4 },
  { "id": 17, "title": "Revenue Optimization Simulation", "creatorId": 4 },
  { "id": 18, "title": "Customer Segmentation Insight", "creatorId": 5 },
  { "id": 19, "title": "Risk Assessment Report", "creatorId": 5 },
  { "id": 20, "title": "Product Development Strategy", "creatorId": 5 },
  { "id": 21, "title": "Investment Portfolio Analysis", "creatorId": 5 },
  { "id": 22, "title": "Resource Allocation Plan", "creatorId": 5 },
  { "id": 23, "title": "Competitive Landscape Mapping", "creatorId": 6 },
  { "id": 24, "title": "User Engagement Metrics", "creatorId": 6 },
  { "id": 25, "title": "Healthcare Outcomes Research", "creatorId": 6 },
  { "id": 26, "title": "Market Trend Analysis", "creatorId": 6 },
  { "id": 27, "title": "Consumer Behavior Study", "creatorId": 6 },
  { "id": 28, "title": "Sales Forecast Model", "creatorId": 7 },
  { "id": 29, "title": "Operational Efficiency Review", "creatorId": 7 },
  { "id": 30, "title": "Revenue Optimization Simulation", "creatorId": 7 },
  { "id": 31, "title": "Customer Segmentation Insight", "creatorId": 7 },
  { "id": 32, "title": "Risk Assessment Report", "creatorId": 7 },
  { "id": 33, "title": "Product Development Strategy", "creatorId": 8 },
  { "id": 34, "title": "Investment Portfolio Analysis", "creatorId": 8 },
  { "id": 35, "title": "Resource Allocation Plan", "creatorId": 8 },
  { "id": 36, "title": "Competitive Landscape Mapping", "creatorId": 8 },
  { "id": 37, "title": "User Engagement Metrics", "creatorId": 8 },
  { "id": 38, "title": "Healthcare Outcomes Research", "creatorId": 8 },
  { "id": 39, "title": "Market Trend Analysis", "creatorId": 9 },
  { "id": 40, "title": "Consumer Behavior Study", "creatorId": 9 },
  { "id": 41, "title": "Sales Forecast Model", "creatorId": 9 },
  { "id": 42, "title": "Operational Efficiency Review", "creatorId": 9 },
  { "id": 43, "title": "Revenue Optimization Simulation", "creatorId": 9 },
  { "id": 44, "title": "Customer Segmentation Insight", "creatorId": 9 },
  { "id": 45, "title": "Risk Assessment Report", "creatorId": 2 },
  { "id": 46, "title": "Product Development Strategy", "creatorId": 2 },
  { "id": 47, "title": "Investment Portfolio Analysis", "creatorId": 2 },
  { "id": 48, "title": "Resource Allocation Plan", "creatorId": 2 },
  { "id": 49, "title": "Competitive Landscape Mapping", "creatorId": 9 },
  { "id": 50, "title": "User Engagement Metrics", "creatorId": 3 },
  { "id": 51, "title": "Healthcare Outcomes Research", "creatorId": 2 },
  { "id": 52, "title": "Market Trend Analysis", "creatorId": 4 },
  { "id": 53, "title": "Consumer Behavior Study", "creatorId": 4 },
  { "id": 54, "title": "Sales Forecast Model", "creatorId": 4 },
  { "id": 55, "title": "Operational Efficiency Review", "creatorId": 4 },
  { "id": 56, "title": "Revenue Optimization Simulation", "creatorId": 4 },
  { "id": 57, "title": "Customer Segmentation Insight", "creatorId": 5 },
  { "id": 58, "title": "Risk Assessment Report", "creatorId": 5 },
  { "id": 59, "title": "Product Development Strategy", "creatorId": 5 },
  { "id": 60, "title": "Investment Portfolio Analysis", "creatorId": 5 },
  { "id": 61, "title": "Resource Allocation Plan", "creatorId": 5 },
  { "id": 62, "title": "Competitive Landscape Mapping", "creatorId": 6 },
  { "id": 63, "title": "User Engagement Metrics", "creatorId": 6 },
  { "id": 64, "title": "Healthcare Outcomes Research", "creatorId": 6 },
  { "id": 65, "title": "Market Trend Analysis", "creatorId": 6 },
  { "id": 66, "title": "Consumer Behavior Study", "creatorId": 6 },
  { "id": 67, "title": "Sales Forecast Model", "creatorId": 7 },
  { "id": 68, "title": "Operational Efficiency Review", "creatorId": 7 },
  { "id": 69, "title": "Revenue Optimization Simulation", "creatorId": 7 },
  { "id": 70, "title": "Customer Segmentation Insight", "creatorId": 7 },
  { "id": 71, "title": "Risk Assessment Report", "creatorId": 7 },
  { "id": 72, "title": "Product Development Strategy", "creatorId": 8 },
  { "id": 73, "title": "Investment Portfolio Analysis", "creatorId": 8 },
  { "id": 74, "title": "Resource Allocation Plan", "creatorId": 8 },
  { "id": 75, "title": "Competitive Landscape Mapping", "creatorId": 8 },
  { "id": 76, "title": "User Engagement Metrics", "creatorId": 8 },
  { "id": 77, "title": "Healthcare Outcomes Research", "creatorId": 8 },
  { "id": 78, "title": "Market Trend Analysis", "creatorId": 9 },
  { "id": 79, "title": "Consumer Behavior Study", "creatorId": 9 },
  { "id": 80, "title": "Sales Forecast Model", "creatorId": 9 },
  { "id": 81, "title": "Operational Efficiency Review", "creatorId": 9 },
  { "id": 82, "title": "Revenue Optimization Simulation", "creatorId": 9 },
  { "id": 83, "title": "Customer Segmentation Insight", "creatorId": 9 },
  { "id": 84, "title": "Risk Assessment Report", "creatorId": 2 },
  { "id": 85, "title": "Product Development Strategy", "creatorId": 2 },
  { "id": 86, "title": "Investment Portfolio Analysis", "creatorId": 2 },
  { "id": 87, "title": "Resource Allocation Plan", "creatorId": 2 },
  { "id": 88, "title": "Competitive Landscape Mapping", "creatorId": 3 },
  { "id": 89, "title": "User Engagement Metrics", "creatorId": 4 },
  { "id": 90, "title": "Healthcare Outcomes Research", "creatorId": 6 },
  { "id": 91, "title": "Market Trend Analysis", "creatorId": 4 },
  { "id": 92, "title": "Consumer Behavior Study", "creatorId": 4 },
  { "id": 93, "title": "Sales Forecast Model", "creatorId": 4 },
  { "id": 94, "title": "Operational Efficiency Review", "creatorId": 4 },
  { "id": 95, "title": "Revenue Optimization Simulation", "creatorId": 4 },
  { "id": 96, "title": "Customer Segmentation Insight", "creatorId": 5 },
  { "id": 97, "title": "Risk Assessment Report", "creatorId": 5 },
  { "id": 98, "title": "Product Development Strategy", "creatorId": 5 },
  { "id": 99, "title": "Revenue Optimization Simulation", "creatorId": 1 }
];